# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NDY0ZGVjMzhlM2M0YmMyYWIxYTUwZmIxNWNmOWQ2YzJiOGExNjIwN2QzYzRjZDM1MTI2MTEwMmRkYTQ2Y2NlMWIyNmJhZjU4MmUxOThmMjdkOGUwZTY2YTRhYTljODFhNWEwMjc2ZjNiMTNlZjk0MGZiOTBmYmEzZTAyMTM3NTE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
